package com.VB_Healthtech_Pvt_Ltd.Vaccine_Buddy.ui.view.Modal.Cart.CartList

data class AskedData(
    val __v: Int,
    val _id: String,
    val addedBy: String,
    val addedFor: String,
    val addressData: List<Any>,
    val appointmentId: String,
    val cartType: String,
    val categoryName: String,
    val consultingFee: String,
    val createdAt: String,
    val description: String,
    val homeVaccinationFee: String,
    val inclusiveVaccine: String,
    val itemStatus: String,
    val noOfDose: String,
    val packageDescription: String,
    val packageId: String,
    val packageImage: String,
    val packageName: String,
    val packagePrice: String,
    val price: String,
    val slot: List<Slot>,
    val slotDay: String,
    val slotDate:String?,
    val status: String,
    val subCategoryName: String,
    val totalConsultantFee: String,
    val totalCost: String,
    val totalPriceOfVaccine: String,
    val totalVaccineFee: String,
    val updatedAt: String,
    val userData: List<UserData>,
    val vaccineDescription: String,
    val vaccineId: String,
    val vaccineImage: String,
    val vaccineName: String,
    val vaccinePrice: String,
    val offerPrice:String,
    val noOfPackageDose:String,
    val userWallet:Int
)