package com.VB_Healthtech_Pvt_Ltd.Vaccine_Buddy.ui.view.Modal.Order.Cancelled

data class OrderData(
    val __v: Int,
    val _id: String,
    val addedBy: String,
    val addedFor: String,
    val addressData: List<AddressData>,
    val approvedStatus: Boolean,
    val cancelAt: String,
    val cartId: String,
    val categoryName: String,
    val completedDose: Int,
    val createdAt: String,
    val customer_number: String,
    val daysArray: List<String>,
    val description: String,
    val doseInfo: List<Any>,
    val gstAmount: String,
    val homeVaccineFee: String,
    val inclusiveVaccine: Int,
    val itemData: List<Any>,
    val itemId: String,
    val itemImage: String,
    val itemName: String,
    val itemPrice: String,
    val itemStatus: String,
    val noOfDose: String,
    val noOfPackageDose: String,
    val order_number: String,
    val order_type: String,
    val packagePrice: String,
    val paymentDetails: PaymentDetails,
    val pendingDose: Int,
    val refundAmount: String,
    val slot: List<Slot>,
    val slotDate: String,
    val slotDay: String,
    val status: String,
    val subCategoryName: String,
    val updatedAt: String,
    val userData: List<UserData>,
    val userName: String,
    val discount:String,
    val discountAmount:String,
    val offerPrice:String,
    val withoutGstAmount: String
)