package com.VB_Healthtech_Pvt_Ltd.Vaccine_Buddy.ui.view.Modal.CheckOutCart

data class AddOrder(
    val __v: Int,
    val _id: String,
    val addedBy: String,
    val addedFor: String,
    val addressData: List<AddressData>,
    val cartId: String,
    val categoryName: String,
    val completedDose: Int,
    val createdAt: String,
    val customer_number: String,
    val description: String,
    val doseInfo: List<Any>,
    val inclusiveVaccine: Int,
    val itemData: List<Any>,
    val itemId: String,
    val itemImage: String,
    val itemName: String,
    val itemPrice: String,
    val itemStatus: String,
    val noOfDose: String,
    val order_number: String,
    val order_type: String,
    val packagePrice: String,
    val pendingDose: Int,
    val slot: List<Slot>,
    val slotDate: String,
    val slotDay: String,
    val status: String,
    val subCategoryName: String,
    val updatedAt: String,
    val userData: List<UserData>,
    val userName: String
)