package com.VB_Healthtech_Pvt_Ltd.Vaccine_Buddy.ui.view.Modal.OrderDetails

import com.amazonaws.services.s3.model.ObjectListing
import java.io.Serializable

data class AskedData(
    val __v: Int,
    val _id: String,
    val addedBy: String,
    val addedFor: String,
    val addressData: ArrayList<AddressData>,
    val cartId: String,
    val approvedStatus:Boolean,
    val categoryName: String,
    val completedDose: Int,
    val createdAt: String,
    val customer_number: String,
    val daysArray: List<String>,
    val description: String,
    val doseInfo: List<DoseInfo>,
    val doseRecord: List<DoseRecord>,
    val gstAmount: String,
    val homeVaccineFee: String,
    val inclusiveVaccine: Int,
    val itemData: List<Any>,
    val itemId: String,
    val itemImage: String,
    val itemName: String,
    val itemPrice: String,
    val itemStatus: String,
    val noOfDose: String,
    val order_number: String,
    val order_type: String,
    val packagePrice: String,
    val paymentDetails: PaymentDetails,
    val pendingDose: Int,
    val slot: List<Slot>,
    val slotDate: String,
    val slotDay: String,
    val status: String,
    val invoiceLink:String?,
    val subCategoryName: String,
    val updatedAt: String,
    val userData: List<UserData>,
    val userName: String,
    val withoutGstAmount: String,
    val assignedCenter:String,
    val assignedNurse:String,
    val discount:String,
    val offerPrice:String,
    val paymentStatus:Boolean,
    val discountAmount:String,
    val packageCertificateLink:String?,

):Serializable