package com.VB_Healthtech_Pvt_Ltd.Vaccine_Buddy.ui.view.Modal.MemberRecord

data class Record(
    val __v: Int,
    val _id: String,
    val ageOfBaby: String?,
    val appointmentId: String,
    val batchNumber: String,
    val categoryName: String,
    val certificate: String,
    val certificateLink: Any,
    val completeDate: String?,
    val completeDosage: Int,
    val createdAt: String,
    val doseInfo: List<DoseInfo>,
    val hight: String,
    val includedVaccine: Int,
    val inclusion: ArrayList<Inclusion>,
    val itemType: String,
    val memberId: String,
    val nurseId: String,
    val nurseName: String?,
    val packageId: String,
    val packageName: String,
    val pendingDosage: Int,
    val price: String,
    val slot: List<SlotX>,
    val slotDate: String,
    val slotDay: String,
    val status: String?,
    val subCategoryName: String,
    val updatedAt: String,
    val user_id: String,
    val vaccines: List<String>?,
    val weight: String
)